### DISCUSSION TITLE
Spring Batch tables are not automatically created with multiple datasources using Spring Boot

### DISCUSSION THREAD

**Discussion by Sax388** [spring-projects/spring-batch#4612] [Q&A] [answered]
I've read https://github.com/spring-projects/spring-boot/issues/33526 and am using
```yaml
spring:
  batch:
    job:
      # Don't run job on application startup
      enabled: false
    jdbc:
      initialize-schema: always
```
I've got multiple datasources and one is marked as `@Primary`.

There's no error message so I don't know to debug it. How can I find out, what I'm missing?
