### ISSUE TITLE
JpaCursorItemReader read all rows in memory even though the cursor batch size is set

### ISSUE THREAD

**Issue by han1448** [spring-projects/spring-batch#4157]
**Bug description**
I am trying to read a large amount of data from postgresql using `JpaCursorItemReader`.
The postgresql driver basically reads all rows when using a cursor, so there is an OutOfMemoryError issue in this case.
https://jdbc.postgresql.org/documentation/head/connect.html#connection-parameters
I set the fetch size supported by the postgresql driver, but it didn't work.

I also set jdbc fetch size supported by hibernate, but it didn't work as intended.
https://vladmihalcea.com/resultset-statement-fetching-with-jdbc-and-hibernate/

However, if I changed to `JdbcCursorItemReader` instead of `JpaCursorItemReader` , both settings above worked as intended.

**Environment**
- java: java 11
- postgresql: 12.6
- spring-boot: 2.5.6
- spring-boot-starter-batch: 2.5.6 
- spring-boot-starter-data-jpa: 2.5.6

**Steps to reproduce**
```yaml
## Set hibernate fetch size
spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          fetch_size: 100

## Or jdbc driver fetch size
spring:
  datasource:
    hikari:
      pool_name: primaryPool
      driver-class-name: "org.postgresql.Driver"
      dataSourceProperties:
        defaultRowFetchSize: 100
```
```kotlin
    @Bean
    fun reader(): ItemReader<TestEntity> {
        return JpaCursorItemReaderBuilder<TestEntity>()
            .entityManagerFactory(entityManagerFactory)
            .queryString(
                """
                SELECT c FROM com.test.TestEntity c
                """
            )
            .build()
    }
```

Below is a snapshot screen of JVM memory in real situation.
And the query is still waiting to read all the data.
<img width="557" alt="스크린샷 2022-07-05 오후 6 22 08" src="https://user-images.githubusercontent.com/4098287/179681486-42963298-8027-43a5-bc50-450816e772c6.png">

**Expected behavior**
If `fetchSize` is set like `JdbcCursorItemReader`, data as much as fetchSize should be read from the cursor.
Most likely we won't notice unless it's a large amount of data.
After setting yaml in the same way as above, data is read normally as much as fetchSize without setting fetchSize in `JdbcCursorItemReader`.

```kotlin
    override fun getReader(): ItemReader<TestEntity> {
        return JdbcCursorItemReaderBuilder<TestEntity>()
//            .fetchSize(100)
            .dataSource(datasource)
            .rowMapper(BeanPropertyRowMapper(TestEntity::class.java))
            .sql("SELECT id FROM test")
            .build()
    }
```

I want JpaCursorItemReader to behave the same as the jdbc driver setting and hiberhante fetch size setting of JdbcCursorItemReader .
