### ISSUE TITLE
Forks fail on GitHub Actions Continuous Inspection Build

### ISSUE THREAD

**Issue by robertmcnees** [spring-projects/spring-batch#4346]
After forking spring-batch the GitHub Actions workflow "Continuous Inspection" repeatedly fails.  The exact error message is:

```Error:  SonarQube server [] can not be reached```

And is likely because the secrets cannot be accessed in a fork.
```
    - name: Analyse code quality with Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        run: mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
```
